### ISSUE TITLE
Se puede llegar a confundir la generación de claves

### ISSUE THREAD

**Issue by angelocho** [gonzaleztroyano/ASIR2-SYAD-P1#13]
En la automatización del rsync se puede llegar a confundir dónde se hace. Si en el cliente o en el servidor por lo de user@server....

**Comment by gonzaleztroyano** [comment]
Recibido!

**Comment by gonzaleztroyano** [comment]
Hola, @Angelocho:

En [este commit](https://github.com/gonzaleztroyano/ASIR2-SYAD-P1/commit/1369a2975679de03d0a2c3c0c158d57f20a823e0) he intentado explicar mejor la parte de Rsync automatizada. 

He cambiado el PS1 de los promts a server/cliente, a ver si se entiende mejor así. También he añadido comentarios sobre la ubicación de ejecución de los comandos. 

Marco como cerrada esta issue. Si tienes alguna queja más puedes reabrirla enviándome un bizum 🙃. 

En bromi, los comentarios son siempre bienvenidos.
